Wikia/api-gateway

README.md
spec/auth_spec.lua
spec/cookie_spec.lua
src/auth.lua
src/gateway/helios.lua
src/mocks/gateway/helios.lua

Change `session_token` to `access_token` so we are consistent with the other services.
/cc @ArturKlajnerok @nmonterroso

Change session_token to access_token

---

nginx/production/api-gateway.conf
spec/nginx_spec.lua
src/nginx.lua

Based on @pchojnacki suggestion, I separated the services and helios `server` blocks onto separate ports. This has the following effects:
* Removes the need for regex replacement of `/service` in the VCL
* Removes the need to pass the URI to the sub request within nginx when proxying to services.
* Simplifies the pass through auth handling
* Fixes the passing of query parameters (nginx was stripping them under the previous config)
* Moves helios to port 8200
This should be 100% backwards compatible with the existing configuration.
/cc @pchojnacki @frankfarmer

Separate ports for helios and services in the api-gateway

---

nginx/conf/nginx.conf
nginx/production/api-gateway.conf

Add a `/helios/register` URI & rate limit it. The nginx documentation is [here](http://nginx.org/en/docs/http/ngx_http_limit_req_module.html).
https://wikia-inc.atlassian.net/browse/SERVICES-31
The corresponding chef-repo pull request is https://github.com/Wikia/chef-repo/pull/5277 for the `http` level directive `limit_req_zone`.
/cc @Wikia/services-team

SERVICES-324 Add /helios/register URI & rate limit

---

nginx/production/api-gateway.conf

Add the resolver back into the nginx. It's required for internal lua DNS resolution. This is specifically for the [request that happens here](https://github.com/Wikia/api-gateway/blob/master/src/gateway/helios.lua#L26) to helios using the `HELIOS_URL` from the config.
https://wikia-inc.atlassian.net/browse/SERVICES-457
/cc @Wikia/services-team

Add the resolver back into the nginx config

---

nginx/production/api-gateway.conf
spec/cors_spec.lua
src/cors.lua
src/nginx/net.lua
src/nginx/scripts/add_cors_headers.lua
templates/conf/upstreams.conf

This change fixes potential errors caused by malformed upstreams.conf
Also Most of the CORS functionality was implemented previously but the filter wasn't enabled so it wasn't working.
Here I reintroduce CORS support with additional headers and setting making api-gateway the authoritative entity WRT to CORS headers. 
As API-Gateway *will* override all existing cors headers set by services. In an effort to standardize the CORS policies across services.
/cc: @kvas-damian @Wikia/services-team @jimmordino @ArturKlajnerok

Fixes nginx errors and re-adds CORS support

---

README.md
nginx/production/api-gateway.conf
spec/auth_spec.lua
spec/nginx_spec.lua
spec_integration/service_auth_spec.lua
src/auth.lua
src/cookie.lua
src/mocks/auth.lua
src/nginx.lua

Add support for authentication via X-Wikia-AccessToken. This supplements the `access_token` cookie to enable authenticated request support for mobile applications. See https://wikia-inc.atlassian.net/browse/SERVICES-399.
/cc @Wikia/services-team

Add support for auth via X-Wikia-AccessToken

---

src/cors.lua

Access-Control-Allow-Methods need to be passed explicitly as wildcard don't work properly with preflighted requests that use OPTIONS method.
/cc @Wikia/services-team @pchojnacki @bkoval @kvas-damian

[SERVICES-531] Added explicit access controll allow methods

---

.travis.yml
nginx/production/api-gateway.conf
src/nginx/router.lua

This merges /helios and & /auth under one route while keeping the rate limiting intact. I also created a helper to simplify the request routing and reduce the duplicated code between the service route and the helios specific route.
This assumes that both `helios` and `auth` are configured in consul for the API gateway. But otherwise they both use the same routing mechanism as every other service.
https://wikia-inc.atlassian.net/browse/SERVICES-568
https://wikia-inc.atlassian.net/browse/SERVICES-555
/cc @Wikia/services-team @pchojnacki

Make /helios & /auth synonymous

---

src/nginx.lua

@Wikia/services-team 
also clear out the `X-Wikia-AccessToken` header when forwarding requests to services

also clear the access token header when forwarding a request to services

---

.travis.yml
api_gateway-0.1-0.rockspec
rockspec

Using rockspec allows for standard way to install all dependencies of the project.
Additionally travis introduced newer faster way to build applications.
This travis config change enables faster builds and hence shorter turnaround time for PRs

Make travis use containers and rockspec to build and test the api-gateway

---

monitoring/health-monitor.py

This was a quickly hacked together script to monitor the gateway for either non-200, lengthy, or failed connections to the api-gateway (or an URL really) health check URI.
https://wikia-inc.atlassian.net/browse/SERVICES-769

Add a simple polling health monitor

---

src/cors.lua

@bkoval reported an issue with sending specific content type to clickstream from browser.
This PR should address this issue
Todo:

SOC-1268/SOC-1317 explicitly list allowed headers. * is not working on both chrome and FF

---

scripts/templatize

This is solely for the scripts/templatize helper. If you don't have `WIKIA_ENVIRONMENT` set the template building won't work because the KV path won't be properly constructed.

Set the WIKIA_ENVIRONMENT to a sane default

---

nginx/production/api-gateway.conf

The `/auth/token` path was not part of the rate limiting in the API gateway. 
https://wikia-inc.atlassian.net/browse/SERVICES-667

Add /auth/token to the rate limiting

---

nginx/production/api-gateway.conf

This PR denies access to user specific token resources under `/auth/users/(\w+)/tokens`. As part of this change I also simplified the handling of `/auth` by nesting the related logic and removing `/helios`. I also explicitly deny access to `/helios` just to be sure there is no way around the other restrictions on `/auth.
https://wikia-inc.atlassian.net/browse/SERVICES-894

Deny access to user specific token resources

---

nginx/production/api-gateway.conf

Restored rate limiting only on `/auth/(token|users|facebook/users)` instead of rate limiting all of `/auth`. Upon deploy of the previous release we discovered that there are some `/auth` paths (e.g. username and token validation) that were being rate limited.
https://wikia-inc.atlassian.net/browse/SERVICES-894
/cc @Wikia/services-team

Restore explicit rate limiting

---

api_gateway-0.1-0.rockspec
spec/auth_spec.lua
src/auth.lua

If multiple `Cookie` headers are provided in the request `ngx.req.headers()['Cookie']` will return a table (array) with each element being the cookie string that was supplied in each header. This PR adds support for table (array) handling of `Cookie` headers.
https://wikia-inc.atlassian.net/browse/SERVICES-1054

Add support for handling cookies as a table of cookies

---

api_gateway-0.1-0.rockspec
nginx/production/api-gateway.conf

Block `/auth/info` in the gateway. Token validation should now be internal only now that we have the whoami service (available via `/whoami`).
https://wikia-inc.atlassian.net/browse/SERVICES-885
@Wikia/services-team @kvas-damian

Block /auth/info

---

.gitignore
.travis.yml
README.md
scripts/install-luarocks.sh
scripts/install-openresty.sh
scripts/run-tests.sh
spec/nginx_spec.lua
src/nginx.lua
src/nginx/router.lua
t/TestHelper.pm
t/basic.t
t/sandbox.t

This PR adds:
- pass through support for the `Fastly-Client-IP` header as `X-Forwarded-For`
- add tests for the pass through using `Test::Nginx::Socket`
Adding the testing revealed the need to break out some of the nginx configuration into separate files. This will allow the request logic to be included in the production ready nginx config and the tests.
https://wikia-inc.atlassian.net/browse/SERVICES-373
TODO:
@jcellary @macbre @Wikia/services-team

WIP: Pass through the Fastly-Client-IP

---

nginx/production/api-gateway.conf
spec/nginx_spec.lua
src/nginx.lua

We are now using the [`Fastly-Client-IP` as the "trusted" source for the client IP](https://github.com/Wikia/chef-repo/pull/7720). This means than in nginx the `$remote_addr` value should now be the "real" client and not a fastly or Wikia POP.
This PR reverts the manual setting of the `X-Forwarded-For` and sets this value using `$remote_addr`.
https://wikia-inc.atlassian.net/browse/SERVICES-373

Use $remote_addr to set X-Forwarded-For

---

.gitignore
README.md
nginx/production/api-gateway.conf
scripts/install-openresty.sh
src/nginx.lua
t/TestHelper.pm
templates/src/config.lua

@Wikia/services-team 
https://wikia-inc.atlassian.net/browse/SERVICES-1147
Rather than relying on a hardcoded url for helios, have the API gateway use the same upstreams it has configured when checking against a token. By default, it will use the same upstream that the `auth` service has defined. This will allow us to have `unavailable` serve requests in Reston using the same configuration we're already using (API gateway routing).

Use "auth" upstream when checking token info

---

templates/src/config.lua

As the subject says. It looks like `key_or_default` isn't available with our version of `consul-template`.
@nmonterroso

Change to key instead of key_or_default

---

src/cors.lua

@Wikia/services-team 
https://wikia-inc.atlassian.net/browse/SERVICES-1238
Adding `X-Wikia-AccessToken` and `X-Proof-Of-Work` to accepted headers when checking `Access-Control-*` headers at the api gateway.

accept x-wikia-accesstoken and x-proof-of-work in ajax requests

---

README.md
scripts/start-nginx
scripts/templatize

Update the api-gateway installation instructions for OS X. Installing the dependencies for the api-gateway on OS X is currently problematic mainly because of some ongoing issues with `luarocks`. This update adds a little more structure to the instructions as well as a trouble shooting guide.
I also automated some of the missing directory creation. That way it should be more clear why nginx is failing and what you need to do about it.

Update the api-gateway installation instructions

---

nginx/production/api-gateway.conf

The `/token` resource should not be exposed to the outside. We can make this internal only by adding the `internal` directive. All external requests will then get a 404.
I manually confirmed that this works as expected. The internal request still work and the `X-Wikia-UserId` header is added as expected.
https://wikia-inc.atlassian.net/browse/SERVICES-1064

Make the /token resource internal-only

---

src/request_headers.lua

The Social team would like to start using the schwartz token as a header in order to validate an internal request. As part of that, we'd like to make sure that header can't be set from outside the gateway. This PR adds a `X-Wikia-Schwartz` header to the list of headers which are filtered out by the gateway.
cc @Wikia/services-team

Don't proxy the X-Wikia-Schwartz token
